#!/usr/bin/env python3
"""Generate firmware/src/font8x16.h from GNU Unifont (printable ASCII 0x20-0x7E).

GNU Unifont 15.x is dual-licensed GPLv2+ (with font embedding exception) / SIL OFL 1.1.
Usage: tools/genfont.py [path/to/unifont.otf] > firmware/src/font8x16.h
"""
import sys
from PIL import Image, ImageDraw, ImageFont

path = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/fonts/opentype/unifont/unifont.otf"
font = ImageFont.truetype(path, 16)

out = ["// Generated by tools/genfont.py from GNU Unifont (OFL-1.1 / GPLv2+ w/ font exception).",
       "// 8x16, one byte per row, MSB = leftmost pixel. Glyphs 0x20..0x7E.",
       "#pragma once", "#include <stdint.h>",
       "#define FONT_W 8", "#define FONT_H 16", "#define FONT_FIRST 0x20", "#define FONT_LAST 0x7E",
       "static const uint8_t font8x16[95][16] = {"]
for c in range(0x20, 0x7F):
    img = Image.new("1", (8, 16), 0)
    d = ImageDraw.Draw(img)
    # Unifont OTF ascent is 14px at size 16; draw at origin so the 16px cell maps 1:1.
    d.text((0, 0), chr(c), font=font, fill=1)
    rows = []
    for y in range(16):
        b = 0
        for x in range(8):
            if img.getpixel((x, y)):
                b |= 0x80 >> x
        rows.append(b)
    out.append("  {" + ",".join(f"0x{b:02x}" for b in rows) + f"}}, // {chr(c)!r}")
out.append("};")
print("\n".join(out))
